export interface StateInfo {
  established: number
  originalCode: string
  capital: string
  population: string
  timezone: string
  majorCities: string[]
  mapZoom: number
  overview: string
  history: string
  businessContext: string
}

export const STATE_DATA: Record<string, StateInfo> = {
  alabama: {
    established: 1947, originalCode: "205", capital: "Montgomery",
    population: "5.1 million", timezone: "Central (CT)",
    majorCities: ["Birmingham", "Huntsville", "Mobile", "Montgomery"],
    mapZoom: 7,
    overview: "Alabama spans the southeastern United States, anchored by Birmingham's industrial legacy, Huntsville's aerospace corridor, and Mobile's Gulf Coast port economy.",
    history: "Alabama entered the North American Numbering Plan in 1947 with a single area code — 205 — covering the entire state. As Birmingham's metro expanded and Huntsville's NASA-driven tech boom accelerated through the 1990s, the single-code system hit capacity limits. The 334 area code was carved out in 1995 to serve central and southern Alabama including Montgomery and Mobile, while the 256 code was introduced in 1998 for the northern region. Today the state's three active codes reflect three distinct economic and demographic zones.",
    businessContext: "Alabama businesses in aerospace (Huntsville), automotive manufacturing (Tuscaloosa), and logistics (Mobile port) use local area codes to build regional credibility and reduce call abandonment from customers wary of out-of-state numbers.",
  },
  alaska: {
    established: 1947, originalCode: "907", capital: "Juneau",
    population: "736,000", timezone: "Alaska (AKT)",
    majorCities: ["Anchorage", "Fairbanks", "Juneau", "Sitka"],
    mapZoom: 4,
    overview: "Alaska, the largest U.S. state by area, has maintained a single area code since 1947 — a rare distinction reflecting its sparse population distribution across vast terrain.",
    history: "Alaska has operated under the single 907 area code since the NANP launched in 1947, and it remains one of the few states that has never needed to split or overlay its original code. Despite being the largest U.S. state by geography — larger than Texas, California, and Montana combined — Alaska's population of under 750,000 residents has never stressed the 907 number pool. The state's unique telecom infrastructure, built to serve remote villages, oil fields, and military installations, has evolved significantly but always under that original code.",
    businessContext: "Anchorage-based businesses in oil services, tourism, and logistics rely on the 907 code to signal local roots, while remote operators use virtual 907 numbers to maintain a professional presence without fixed infrastructure.",
  },
  arizona: {
    established: 1947, originalCode: "602", capital: "Phoenix",
    population: "7.4 million", timezone: "Mountain (no DST)",
    majorCities: ["Phoenix", "Tucson", "Mesa", "Scottsdale", "Chandler"],
    mapZoom: 7,
    overview: "Arizona's dramatic population growth over the past four decades has made it one of the fastest-expanding telecom markets in the country, producing six active area codes centered on Phoenix's sprawling metro.",
    history: "Arizona launched with area code 602 in 1947, covering the entire state from Phoenix to Tucson. The state's explosive population growth — driven by retirees, tech migration, and Sun Belt urbanization — quickly overwhelmed the original code. The 520 area code split off in 1995 to cover Tucson and southern Arizona. Phoenix's ongoing boom then required 480 for the East Valley (1999), 623 for the West Valley (1999), and 928 for northern and western Arizona (2001). A second wave of population pressure brought the 602 overlay 480 supplemental codes in later years, reflecting Phoenix's status as the fifth-largest U.S. city.",
    businessContext: "Phoenix's tech sector (Intel, Apple, Amazon), Tucson's bioscience clusters, and Scottsdale's financial services firms all use local area codes to demonstrate community presence in markets that move rapidly and value local identity.",
  },
  arkansas: {
    established: 1947, originalCode: "501", capital: "Little Rock",
    population: "3.1 million", timezone: "Central (CT)",
    majorCities: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale"],
    mapZoom: 7,
    overview: "Arkansas is anchored by Little Rock in the center and the booming Northwest Arkansas corridor — home to Walmart's global headquarters — in the northwest.",
    history: "Arkansas launched under area code 501 in 1947, serving the entire state for almost five decades. The rise of Northwest Arkansas as a major corporate and logistics hub, driven by Walmart, Tyson Foods, and J.B. Hunt, created enough subscriber demand to necessitate a geographic split. The 870 area code was introduced in 1997 to serve eastern and southern Arkansas, while 501 was retained for Little Rock and central regions. Northwest Arkansas eventually got its own identity within 479, split from 501 in 2002 to serve the Fayetteville-Springdale-Rogers metropolitan area.",
    businessContext: "Arkansas businesses in retail supply chain, agriculture, and transportation use local codes to build regional trust with suppliers and customers who recognize 501, 479, and 870 as markers of genuine local operations.",
  },
  california: {
    established: 1947, originalCode: "415", capital: "Sacramento",
    population: "39.5 million", timezone: "Pacific (PT)",
    majorCities: ["Los Angeles", "San Francisco", "San Diego", "San Jose", "Sacramento"],
    mapZoom: 6,
    overview: "California is the most telephonically complex state in the country, with over 35 active area codes reflecting the world's fifth-largest economy and its concentration of global technology, entertainment, and agricultural industries.",
    history: "California entered the NANP in 1947 with a small handful of area codes — 415 for Northern California, 213 for Southern California, and 916 for Sacramento. Over the following decades, California's relentless population and business growth triggered the most aggressive area code expansion in U.S. history. Los Angeles alone has spawned 213, 310, 323, 424, 562, 626, 657, 661, 714, 747, 818, 909, and others. The Bay Area generated 408, 415, 510, 650, 669, 707, 925, and additional overlays as Silicon Valley became the global center of technology. By the 2020s, California required constant management of its number pools to sustain the world's largest concentration of mobile and VoIP subscribers outside of China.",
    businessContext: "California's diversity of markets — Silicon Valley tech, LA entertainment, San Diego biotech, Central Valley agriculture, and LA-area logistics — means local area codes are critical differentiators that signal which market a business genuinely serves.",
  },
  colorado: {
    established: 1947, originalCode: "303", capital: "Denver",
    population: "5.9 million", timezone: "Mountain (MT)",
    majorCities: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Boulder"],
    mapZoom: 7,
    overview: "Colorado's tech-driven economy, anchored by Denver's growing metropolitan area and Boulder's startup ecosystem, has made it one of the fastest-growing telecom markets in the Mountain West.",
    history: "Colorado was assigned area code 303 at the launch of the NANP in 1947, covering the entire state. Colorado Springs and the southern region were split off with area code 719 in 1988 — one of the earlier geographic splits in U.S. history, reflecting Colorado Springs' rapid military and suburban growth. Denver's continued expansion prompted the addition of area code 970 for the Western Slope and Northern Front Range in 1995. The metro Denver region then received the 720 overlay in 1999 as cell phones and internet connections consumed the remaining 303 numbers. Today, Denver is one of the top five U.S. cities for tech company relocations, and its codes reflect decades of growth.",
    businessContext: "Colorado businesses in aerospace (Lockheed Martin, Boeing), renewable energy, outdoor recreation, and technology use 303 and 720 numbers to signal Denver metro credibility with customers across the Mountain West region.",
  },
  connecticut: {
    established: 1947, originalCode: "203", capital: "Hartford",
    population: "3.6 million", timezone: "Eastern (ET)",
    majorCities: ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury"],
    mapZoom: 9,
    overview: "Connecticut is one of the nation's wealthiest states per capita, home to major financial services, insurance, pharmaceutical, and defense industries concentrated in the southwestern Fairfield County corridor.",
    history: "Connecticut entered the NANP in 1947 under area code 203, which served the entire state for nearly five decades. The population density of southwestern Connecticut — particularly Fairfield County's commuter-to-New-York communities and Stamford's financial district — drove subscriber demand that eventually exceeded the 203 pool. In 1995, the 860 area code was split off to serve Hartford, New Haven (partially), and northern Connecticut, while 203 was retained for the southwestern corner. This split created a clear divide between Connecticut's two economic identities: the Wall Street corridor and the Hartford insurance capital.",
    businessContext: "Connecticut's financial services firms (hedge funds, insurance companies), pharmaceutical manufacturers, and defense contractors in the Sikorsky corridor use local 203 and 860 numbers to maintain credibility with clients on both the New York financial axis and New England supply chains.",
  },
  delaware: {
    established: 1947, originalCode: "302", capital: "Dover",
    population: "1.0 million", timezone: "Eastern (ET)",
    majorCities: ["Wilmington", "Dover", "Newark", "Middletown"],
    mapZoom: 9,
    overview: "Delaware remains one of the few states with a single area code — 302 — reflecting its compact geography and status as the corporate capital of America, home to more than 1.8 million registered businesses.",
    history: "Delaware has operated under area code 302 since the NANP's launch in 1947 and has never required a split or overlay. Despite incorporating over 1.8 million businesses (more than the state's actual human population), Delaware's subscriber demand has remained manageable because most registered businesses are shell corporations that maintain minimal telephony infrastructure in the state. Wilmington's banking corridor — home to Bank of America, JPMorgan Chase, and Capital One's credit card operations — drives the highest volume of legitimate 302 subscribers, but the state's small physical size has kept the single-code system viable.",
    businessContext: "Delaware's corporate law and banking infrastructure make 302 numbers a prestige signal for financial services, legal, and holding companies that need a credible Delaware presence without a full physical office.",
  },
  "district of columbia": {
    established: 1947, originalCode: "202", capital: "Washington D.C.",
    population: "689,000", timezone: "Eastern (ET)",
    majorCities: ["Washington D.C."],
    mapZoom: 11,
    overview: "The District of Columbia operates under the single 202 area code — one of the most recognized codes in the country and a signal of proximity to federal government and policy-making.",
    history: "Washington D.C. received area code 202 at the launch of the NANP in 1947 and has maintained it exclusively ever since. The District's unique status as a federal jurisdiction — not a state — and its concentrated geography have kept subscriber demand within manageable bounds despite housing the federal government, embassies, major law firms, lobbying organizations, and national media outlets. The 202 code carries distinctive prestige value: it signals proximity to federal power and is considered the most politically significant area code in North America.",
    businessContext: "Government contractors, federal agencies, law firms, think tanks, and advocacy organizations use 202 numbers as a direct signal of Washington D.C. presence — a critical credibility marker when engaging with federal clients, congressional offices, and regulatory bodies.",
  },
  florida: {
    established: 1947, originalCode: "305", capital: "Tallahassee",
    population: "22.6 million", timezone: "Eastern/Central (ET/CT)",
    majorCities: ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg"],
    mapZoom: 6,
    overview: "Florida is the third-most-populous state and one of the fastest-growing telecom markets, with over 20 active area codes spanning vastly different regional economies from Miami's global finance hub to the Panhandle's military-driven economy.",
    history: "Florida launched with area code 305 in 1947, covering the entire state. Explosive population growth driven by retiree migration, tourism, and Latin American immigration has since created one of the most complex area code landscapes in the country. Miami alone generated 305, 786, and 645 overlays. The Tampa-St. Petersburg corridor produced 727 and 813. Central Florida's tourism economy required 321, 407, and 689. Jacksonville got 904, the Panhandle got 850, and Fort Lauderdale's corridor operates under 954. Southwest Florida received 239. The state's number demand continues to grow as Florida added more residents than any other state in the 2020 Census cycle.",
    businessContext: "Florida's mix of real estate, tourism, international banking (Miami), defense contracting (Pensacola-Eglin corridor), and healthcare serves markets that are intensely local — a Miami client will not be impressed by an 850 Panhandle number, making precise area code targeting essential.",
  },
  georgia: {
    established: 1947, originalCode: "404", capital: "Atlanta",
    population: "11.0 million", timezone: "Eastern (ET)",
    majorCities: ["Atlanta", "Augusta", "Columbus", "Macon", "Savannah"],
    mapZoom: 7,
    overview: "Georgia is the economic capital of the American Southeast, anchored by Atlanta's massive metropolitan area — home to Coca-Cola, Delta Air Lines, CNN, and one of the busiest airports in the world.",
    history: "Georgia entered the NANP in 1947 under area code 404, which covered the entire state for decades. Atlanta's explosive growth as the Southeast's dominant economic hub eventually overwhelmed the 404 number pool. The 912 area code split in 1954 to cover southern and coastal Georgia. The Atlanta metro then generated a cascade of additional codes: 770 was introduced in 1995 for Atlanta's suburbs, 678 was added as an overlay in 1998, 470 came as another Atlanta overlay in 2015, and 943 is being introduced for continued growth. Savannah's coastal economy and Augusta's cyber and military presence are served by 912 and 706 respectively.",
    businessContext: "Atlanta's Fortune 500 concentration, Savannah's port and logistics hub, and Augusta's cyber defense corridor all benefit from precise area code targeting — particularly for businesses seeking to differentiate between metro Atlanta and the broader Southeast.",
  },
  hawaii: {
    established: 1947, originalCode: "808", capital: "Honolulu",
    population: "1.4 million", timezone: "Hawaii (HT)",
    majorCities: ["Honolulu", "Pearl City", "Hilo", "Kailua"],
    mapZoom: 7,
    overview: "Hawaii is the only island state and has operated under the single 808 area code since 1947, a fact that has made 808 one of the most regionally distinctive codes in the country.",
    history: "Hawaii entered the NANP in 1947 with area code 808, covering all of the Hawaiian Islands — from Oahu to Maui, the Big Island, and the smaller islands of Kauai, Molokai, and Lanai. Despite being the only state that requires crossing an ocean to reach, Hawaii has maintained a single area code. Tourism's dominance of the economy, the military's presence at Pearl Harbor and other installations, and the state's relatively stable population have kept 808 number demand within available supply. The code has become one of the most recognizable in North America — often associated with vacation, hospitality, and the unique pace of island business.",
    businessContext: "Tourism operators, hospitality businesses, real estate firms, and defense contractors in Hawaii use the 808 code to immediately signal island presence to the millions of visitors and off-island investors who specifically seek out Hawaii-based vendors.",
  },
  idaho: {
    established: 1947, originalCode: "208", capital: "Boise",
    population: "1.9 million", timezone: "Mountain/Pacific (MT/PT)",
    majorCities: ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello"],
    mapZoom: 7,
    overview: "Idaho has grown significantly in recent years as Boise emerged as a major tech hub and the broader Treasure Valley absorbed migration from California and the Pacific Northwest.",
    history: "Idaho has operated under a single area code — 208 — since the NANP's launch in 1947 and maintained it through most of its history. However, the state's rapid population growth in the 2010s and 2020s, driven by tech migration to Boise's emerging Silicon Valley satellite economy, eventually created number demand that a single code could no longer sustain. The 986 overlay was introduced in 2017 to supplement 208 in the Boise metro, representing Idaho's first area code addition in 70 years. The state's nickname 'the next tech hub' is reflected in the accelerating consumption of its phone number pools.",
    businessContext: "Boise's rapidly growing tech and semiconductor sector (Micron Technology's headquarters), Treasure Valley's food processing industry, and outdoor recreation businesses all use Idaho numbers to build trust with a population that places high value on local identity and regional loyalty.",
  },
  illinois: {
    established: 1947, originalCode: "312", capital: "Springfield",
    population: "12.6 million", timezone: "Central (CT)",
    majorCities: ["Chicago", "Aurora", "Joliet", "Rockford", "Springfield"],
    mapZoom: 7,
    overview: "Illinois is the Midwest's dominant economic hub, centered on Chicago — America's third-largest city and one of the world's major financial and logistics centers — served by a dense network of area codes.",
    history: "Illinois launched with area code 312 in 1947, which covered the entire state. Chicago's massive size and economic density made it one of the first metros in the country to require area code relief. Illinois was split into regional codes early: 618 for southern Illinois in 1954, 815 for northern Illinois outside Chicago in 1957, 217 for central Illinois in 1959, and 309 for west-central Illinois in 1959. Chicago's own 312 was later overlaid with 773 (1996) for the city neighborhoods outside the Loop, while the suburbs received 630, 847, 224, and 331. The 708 code was added for the near southwestern suburbs. Chicago's continuing role as a global financial center and commodity trading hub sustains constant demand for new numbers.",
    businessContext: "Chicago's commodities trading firms (CME Group, CBOT), financial institutions, logistics companies (O'Hare positions Illinois as a freight nexus), and professional services firms use specific Chicago-area codes — particularly 312 for the downtown Loop — as prestige signals.",
  },
  indiana: {
    established: 1947, originalCode: "317", capital: "Indianapolis",
    population: "6.8 million", timezone: "Eastern (ET)",
    majorCities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel"],
    mapZoom: 7,
    overview: "Indiana is anchored by Indianapolis — the Crossroads of America — which hosts the nation's most extensive highway system intersection and a growing life sciences and motorsports-related economy.",
    history: "Indiana entered the NANP in 1947 with area code 317 covering the entire state. As Indiana grew and Indianapolis developed into a significant Midwest corporate hub, the state was progressively split. The 812 area code was assigned to southern Indiana, and 219 was introduced for the northwestern corner near Chicago's industrial sphere. The Fort Wayne region received 260, while Indianapolis's growth eventually required the 463 overlay introduced in 2015 alongside the original 317. Indiana's adoption of the Eastern time zone by most of the state (completed in 2006 after decades of controversy) unified its business hours with its largest trading partners.",
    businessContext: "Indianapolis's life sciences cluster (Eli Lilly headquarters), logistics networks, motorsports industry (Indianapolis Motor Speedway), and automotive manufacturing operations in cities like Anderson and Marion all use local Indiana codes to signal regional commitment.",
  },
  iowa: {
    established: 1947, originalCode: "515", capital: "Des Moines",
    population: "3.2 million", timezone: "Central (CT)",
    majorCities: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
    mapZoom: 7,
    overview: "Iowa is the agricultural heartland of the United States, home to the country's largest pork and egg production industries, and increasingly a data center hub due to cheap land, renewable energy, and tax incentives.",
    history: "Iowa entered the NANP in 1947 with area code 515 covering most of the state. The state's three major economic regions — Des Moines in the center, Cedar Rapids in the east, and Sioux City in the west — eventually justified geographic splits. The 319 area code was assigned to eastern Iowa including Cedar Rapids and Iowa City. The 712 code covers western Iowa including Sioux City. Des Moines retained 515 but received the 641 addition for the north-central region. Iowa's data center boom — Microsoft, Facebook/Meta, and Google all operate major facilities here — has added new categories of subscriber demand beyond traditional residential and business lines.",
    businessContext: "Iowa businesses in agriculture (major pork and corn processing), insurance (Principal Financial, Nationwide headquarters in Des Moines), and data center operations use local codes to signal roots in one of the nation's most trust-based, relationship-driven business cultures.",
  },
  kansas: {
    established: 1947, originalCode: "316", capital: "Topeka",
    population: "2.9 million", timezone: "Central (CT)",
    majorCities: ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe"],
    mapZoom: 7,
    overview: "Kansas straddles two economic identities: the wheat-and-aviation economy of the Wichita corridor in the south, and the Kansas City metropolitan area in the northeast — one of the Midwest's most dynamic business communities.",
    history: "Kansas entered the NANP in 1947 under area code 316, which served the entire state. As growth in the Kansas City metro on both sides of the Missouri border accelerated, the state was split. The 913 area code was introduced to serve northeastern Kansas including Kansas City, Overland Park, and the Johnson County corridor — one of the nation's highest-income suburban counties. Wichita retained 316 while central Kansas received the 785 area code for Topeka and the vast agricultural regions. Kansas's aviation industry — Spirit AeroSystems, Cessna, Beechcraft — made Wichita a niche industrial hub with specific telecom needs distinct from the metro.",
    businessContext: "Kansas businesses in aviation manufacturing (Wichita is the 'Air Capital of the World'), agricultural commodities, and the Kansas City metro's financial and tech services market use specific area codes to signal which economic sphere they operate in.",
  },
  kentucky: {
    established: 1947, originalCode: "502", capital: "Frankfort",
    population: "4.5 million", timezone: "Eastern/Central (ET/CT)",
    majorCities: ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"],
    mapZoom: 7,
    overview: "Kentucky is known for bourbon distilling, thoroughbred horse racing, coal (historically), and a growing auto manufacturing sector centered on Toyota's Georgetown plant and Ford's Louisville operations.",
    history: "Kentucky launched with area code 502 in 1947, serving the entire state. As the state's two dominant metros — Louisville in the west and Lexington in the central Bluegrass region — grew, the telecom infrastructure was split. The 606 area code was assigned to eastern Kentucky, including the Appalachian coal country and Ashland's industrial corridor. Lexington eventually received the 859 area code split from 606 in 1999 to reflect the Bluegrass region's distinct economy centered on horses, university activities at UK, and Toyota's supplier ecosystem. Louisville retained 502, reflecting its status as the state's largest city and UPS's global air hub.",
    businessContext: "Kentucky's bourbon industry (a $9 billion annual economic impact), horse racing tourism, automotive manufacturing supply chains, and Louisville's logistics hub (UPS Worldport) all rely on specific area codes to target buyers and partners within their distinct geographic markets.",
  },
  louisiana: {
    established: 1947, originalCode: "504", capital: "Baton Rouge",
    population: "4.6 million", timezone: "Central (CT)",
    majorCities: ["New Orleans", "Baton Rouge", "Shreveport", "Metairie", "Lafayette"],
    mapZoom: 7,
    overview: "Louisiana's economy is driven by petrochemicals along the 'chemical corridor' between Baton Rouge and New Orleans, offshore oil and gas production, agriculture, seafood, and a world-class tourism industry centered on New Orleans.",
    history: "Louisiana was assigned area code 504 in 1947, covering the entire state. The geographic concentration of Louisiana's major industries along the Mississippi River corridor and the distinct cultural identity of New Orleans, Baton Rouge, and Shreveport eventually drove a geographic split. The 318 area code was introduced for northern Louisiana including Shreveport's oil-refining and media markets. Lafayette's Cajun Country and the Acadiana region received 337, while New Orleans retained its original 504. The 225 area code was added for Baton Rouge's petrochemical and government corridor. The aftermath of Hurricane Katrina in 2005 significantly disrupted Louisiana's telecom infrastructure, accelerating the adoption of virtual numbers across businesses that needed to maintain operations during and after displacement.",
    businessContext: "Louisiana's petrochemical industry, offshore oil services, seafood processing, and New Orleans tourism use area codes as geographic identifiers in highly relationship-based industries where local credibility is a prerequisite for contract awards.",
  },
  maine: {
    established: 1947, originalCode: "207", capital: "Augusta",
    population: "1.4 million", timezone: "Eastern (ET)",
    majorCities: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
    mapZoom: 7,
    overview: "Maine is New England's largest state by area and has maintained a single area code since 1947, reflecting its vast geography and relatively small population concentrated in the Portland and Augusta corridors.",
    history: "Maine has operated under area code 207 since the NANP's launch in 1947 and remains one of the few states that has never required an area code split or overlay. Maine's population of approximately 1.4 million, distributed across a large landmass from the Portland metro to the remote northern forests, has never created sufficient subscriber density to exhaust the 207 number pool. The state's economy of tourism, fishing, lobstering, paper mills, and a growing Portland food and tech scene has generated moderate telecom demand. Maine's 207 area code is recognized throughout New England and Canada as a marker of genuine Pine Tree State roots.",
    businessContext: "Maine businesses in lobster and seafood distribution, tourism and hospitality, boat building and marine technology, and Portland's emerging tech startup scene use 207 numbers to signal authenticity in markets where 'made in Maine' carries premium value with both in-state and out-of-state buyers.",
  },
  maryland: {
    established: 1947, originalCode: "301", capital: "Annapolis",
    population: "6.2 million", timezone: "Eastern (ET)",
    majorCities: ["Baltimore", "Columbia", "Germantown", "Silver Spring", "Annapolis"],
    mapZoom: 8,
    overview: "Maryland sits at the intersection of the federal government's orbit, Baltimore's healthcare and port economy, and the dense suburban corridors connecting Washington D.C. to the Chesapeake Bay region.",
    history: "Maryland entered the NANP in 1947 under area code 301, which served the entire state including the heavily populated Washington D.C. suburbs in Montgomery and Prince George's counties. Baltimore's growth and the suburban Washington sprawl created enough demand to split the state. Area code 410 was introduced in 1991 for the Baltimore metro, the Eastern Shore, and southern Maryland — while 301 was retained for the western Maryland and Washington suburbs. Both 301 and 410 then received overlays: 240 for western Maryland/DC suburbs and 443 for Baltimore's metro, both introduced in 1997 and 1998. Maryland's unique position as host to NSA headquarters (Fort Meade), NIH, Johns Hopkins, and USMC bases creates sustained high-volume telecom demand from contractors and agencies.",
    businessContext: "Maryland's defense and intelligence contracting community (centered on the Fort Meade-Annapolis Junction corridor), Johns Hopkins Medicine, Under Armour, and Baltimore's maritime industries all rely on specific 301 or 410 numbers to signal which part of Maryland's complex market they serve.",
  },
  massachusetts: {
    established: 1947, originalCode: "617", capital: "Boston",
    population: "7.1 million", timezone: "Eastern (ET)",
    majorCities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
    mapZoom: 8,
    overview: "Massachusetts is one of the world's premier innovation economies, anchored by Boston and Cambridge's extraordinary concentration of universities, biotech, financial services, and technology companies.",
    history: "Massachusetts entered the NANP in 1947 with area code 617, covering the entire state. Boston's role as New England's economic capital and the epicenter of American higher education created intense subscriber demand that split the state early. The 413 area code was assigned to western Massachusetts including Springfield and the Pioneer Valley. Eastern Massachusetts outside of Boston proper received 508, while the Boston metro retained 617. As cell phones proliferated and Boston's biotech corridor grew through the 1990s and 2000s, additional codes were required: 781 was added for the inner suburbs, 339 as an overlay, and 857 as a Boston overlay. Worcester received 774 as a 508 overlay. Today the Route 128 tech corridor and Kendall Square's biotech cluster sustain some of the highest per-capita area code density in the country.",
    businessContext: "Massachusetts's world-class biotech and pharmaceutical cluster (Kendall Square has more biotech patents per square mile than anywhere on Earth), Harvard-MIT research ecosystem, Fidelity Investments, and State Street Bank all use specific Boston and Route 128 area codes to position within a market that places significant weight on institutional proximity.",
  },
  michigan: {
    established: 1947, originalCode: "313", capital: "Lansing",
    population: "10.1 million", timezone: "Eastern (ET)",
    majorCities: ["Detroit", "Grand Rapids", "Warren", "Ann Arbor", "Sterling Heights"],
    mapZoom: 7,
    overview: "Michigan is the automotive capital of the world, anchored by Detroit's Big Three automakers and their vast supplier networks, and increasingly diversified into defense, mobility technology, and advanced manufacturing.",
    history: "Michigan launched with area code 313 in 1947, covering the entire state. Detroit's status as the center of American manufacturing created dense subscriber demand early. The Upper Peninsula, with its distinct geography and economy, was split off with the 906 area code. Lower Michigan was progressively divided: 616 for western Michigan including Grand Rapids, 517 for the Lansing-Jackson corridor, 810 for the Flint-Saginaw region, and 517 for mid-Michigan. Detroit's metro required repeated relief: 734 was added for western Wayne County and Ann Arbor, 248 for Oakland and Macomb counties, and 586 was split from 810 for Macomb County's dense automotive supplier communities. Ann Arbor's University of Michigan and mobility tech startup scene has added new categories of demand beyond traditional auto industry telephony.",
    businessContext: "Michigan's automotive OEMs and tier-one suppliers use Detroit-area codes (313, 248, 586) as proof of Big Three proximity, while Ann Arbor's mobility and autonomous vehicle companies use 734 to signal tech credentials within the automotive ecosystem.",
  },
  minnesota: {
    established: 1947, originalCode: "612", capital: "Saint Paul",
    population: "5.7 million", timezone: "Central (CT)",
    majorCities: ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington"],
    mapZoom: 7,
    overview: "Minnesota punches above its weight economically, home to more Fortune 500 headquarters per capita than any other state, anchored by the Twin Cities metro that contains Target, Best Buy, UnitedHealth Group, and 3M.",
    history: "Minnesota entered the NANP in 1947 under area code 612, which covered the entire state for several decades. The Twin Cities metro's growth as one of America's most economically productive regions eventually required code relief. The 218 area code was assigned to northern Minnesota including Duluth, while 507 was introduced for southern Minnesota including Rochester (home to Mayo Clinic) and Mankato. 612 was retained for Minneapolis and the immediate metro. As Twin Cities growth continued, the 651 area code was split off for Saint Paul and eastern metro suburbs in 1998. The 952 code was added for the southwestern suburbs including Bloomington, Eden Prairie, and the Mall of America corridor. Rochester's 507 area code has gained particular recognition due to Mayo Clinic's global medical tourism drawing international patients who specifically seek out Rochester-based contact numbers.",
    businessContext: "Minnesota's unusually high concentration of corporate headquarters (Target, Best Buy, 3M, UnitedHealth, General Mills, Cargill) creates a business culture where 612 and 651 Twin Cities numbers carry significant credibility for corporate service providers, consultants, and B2B vendors.",
  },
  mississippi: {
    established: 1947, originalCode: "601", capital: "Jackson",
    population: "3.0 million", timezone: "Central (CT)",
    majorCities: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"],
    mapZoom: 7,
    overview: "Mississippi is anchored by Jackson's state government and healthcare economy in the center, the Gulf Coast's casino and military economy in the south, and a rapidly growing northern region in the Memphis, Tennessee suburban orbit.",
    history: "Mississippi launched with area code 601 in 1947, serving the entire state. As Mississippi's northern suburbs of Memphis (Southaven, Olive Branch, Horn Lake) grew into some of the fastest-expanding areas in the nation, geographic splits became necessary. The 662 area code was introduced in 1999 for northern Mississippi, reflecting the Memphis suburban boom. The 769 area code was introduced as a statewide overlay in 2011, making Mississippi's number system more flexible. Mississippi's Gulf Coast, rebuilt after Hurricane Katrina, has seen significant casino and military base (Keesler Air Force Base) subscriber growth that has been accommodated within the existing code structure.",
    businessContext: "Mississippi businesses in catfish farming (the nation's largest), automotive manufacturing (Nissan, Toyota in the Golden Triangle), and Gulf Coast casino hospitality use local area codes to demonstrate genuine Mississippi presence in trust-sensitive markets.",
  },
  missouri: {
    established: 1947, originalCode: "314", capital: "Jefferson City",
    population: "6.2 million", timezone: "Central (CT)",
    majorCities: ["Kansas City", "Saint Louis", "Springfield", "Columbia", "Independence"],
    mapZoom: 7,
    overview: "Missouri sits at the geographic crossroads of the United States with two major metropolitan areas — St. Louis and Kansas City — each with distinct economic identities and their own area code clusters.",
    history: "Missouri entered the NANP in 1947 with area code 314, which covered the entire state. St. Louis's position as a major river port and industrial center, combined with Kansas City's agricultural and retail trade dominance, created two distinct economic zones that eventually required separate codes. Kansas City and western Missouri received the 816 area code, while Springfield and the Ozarks region got 417. Southern Missouri received 573 (including the Lake of the Ozarks tourism corridor and Jefferson City), and St. Louis's suburban growth required the 636 split from 314. St. Louis later added the 557 overlay. Missouri's position at the confluence of the Missouri and Mississippi rivers, combined with its role as headquarters to Anheuser-Busch (St. Louis) and major agricultural trading companies (Kansas City), gives its area codes distinctive commercial weight.",
    businessContext: "Missouri businesses in craft beer and beverage distribution, agricultural commodities trading, Anheuser-Busch's supply chain, and Kansas City's barbecue and live music tourism use local codes to authenticate their Missouri roots in industries where geographic identity drives premium pricing.",
  },
  montana: {
    established: 1947, originalCode: "406", capital: "Helena",
    population: "1.1 million", timezone: "Mountain (MT)",
    majorCities: ["Billings", "Missoula", "Great Falls", "Bozeman", "Helena"],
    mapZoom: 6,
    overview: "Montana is the fourth-largest U.S. state by area but has maintained a single area code — 406 — since 1947, reflecting its sparse population across vast ranch, forest, and wilderness landscapes.",
    history: "Montana has operated under area code 406 since the NANP's inception in 1947 and has never required a split or overlay. Despite its enormous geographic footprint — larger than Germany — Montana's population of approximately 1.1 million has never created subscriber demand that exceeds the capacity of a single area code. Bozeman's recent emergence as a tech hub attracting remote workers from San Francisco and Seattle has accelerated subscriber growth slightly, and the state has begun planning for number relief, but 406 remains Montana's sole code. The 406 has become an identity marker for Montanans who take pride in the state's wide-open character.",
    businessContext: "Montana businesses in ranching, hunting and fishing outfitting, ski resort operations, and Bozeman's growing tech community use the 406 code to signal genuine Montana presence — particularly important for outdoor recreation and agriculture companies whose customers pay premiums for authentic Rocky Mountain provenance.",
  },
  nebraska: {
    established: 1947, originalCode: "402", capital: "Lincoln",
    population: "2.0 million", timezone: "Central (CT)",
    majorCities: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
    mapZoom: 7,
    overview: "Nebraska is anchored by Omaha — the headquarters city for Berkshire Hathaway, Union Pacific Railroad, Mutual of Omaha, and one of the nation's largest concentrations of Fortune 500 companies per capita.",
    history: "Nebraska launched under area code 402 in 1947. Omaha's remarkable concentration of insurance, financial services, and railroad headquarters created sustained subscriber demand in the eastern part of the state, while the agricultural regions of the Sandhills and Panhandle had much lower density. The 308 area code was introduced in 1999 to serve western and central Nebraska, including Grand Island, Kearney, and the vast ranch lands stretching to Wyoming. Omaha and Lincoln retained 402, reflecting the east-west economic split between the urban/corporate Omaha-Lincoln corridor and the agricultural hinterlands.",
    businessContext: "Nebraska's extraordinary financial services concentration — Berkshire Hathaway, TD Ameritrade (founded in Omaha), Mutual of Omaha, First National Bank of Omaha — makes the 402 area code carry significant weight in financial and insurance industry circles, where an Omaha address signals conservatism, stability, and credibility.",
  },
  nevada: {
    established: 1947, originalCode: "702", capital: "Carson City",
    population: "3.2 million", timezone: "Pacific (PT)",
    majorCities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"],
    mapZoom: 7,
    overview: "Nevada is one of the fastest-growing states in the country, powered by Las Vegas's entertainment and convention economy and Reno's emerging tech and logistics hub in the north.",
    history: "Nevada launched with area code 702 in 1947, covering the entire state when it had a population of just 160,000. Las Vegas's transformation from a small railroad town to the world's entertainment capital drove explosive subscriber growth through the 1970s, 1980s, and 1990s. The Reno-Sparks area and northern Nevada were split off with the 775 area code in 1998, which also covers Lake Tahoe and the rural mining and ranching regions. Las Vegas retained 702 but has since added the 725 overlay as Clark County's population surged past two million. Reno has grown rapidly as Tesla's Gigafactory, Google, Apple, and Amazon established data centers and logistics operations to take advantage of Nevada's tax advantages.",
    businessContext: "Las Vegas's convention and hospitality industry, gaming technology sector, and Nevada's tax-advantaged corporate registration environment make 702 a powerful signal for businesses serving the entertainment industry, while 775 signals Reno's growing tech and logistics credibility.",
  },
  "new hampshire": {
    established: 1947, originalCode: "603", capital: "Concord",
    population: "1.4 million", timezone: "Eastern (ET)",
    majorCities: ["Manchester", "Nashua", "Concord", "Derry", "Dover"],
    mapZoom: 8,
    overview: "New Hampshire has maintained a single area code since 1947 and is notable for its 'Live Free or Die' business environment — no income tax, no sales tax — that has attracted significant corporate relocation from Massachusetts.",
    history: "New Hampshire has operated under area code 603 since the NANP's launch in 1947 and has never split or overlaid its code. Despite sharing a border with Massachusetts and receiving significant overflow population from the Boston metro (southern New Hampshire towns like Nashua and Manchester are part of the Boston commuter economy), the state's total subscriber count has remained within 603's capacity. New Hampshire's lack of income and sales taxes has made it a destination for Massachusetts businesses relocating headquarters, adding corporate subscribers without exhausting the available number pool. The 603 code is recognized throughout New England as a signal of New Hampshire's tax-friendly, libertarian-leaning business culture.",
    businessContext: "New Hampshire businesses use 603 numbers to signal their no-tax advantage to Massachusetts-based clients and employees considering relocation, while hospitality and tourism operators in the White Mountains and Lakes Region use local numbers to build authentic New England credibility.",
  },
  "new jersey": {
    established: 1947, originalCode: "201", capital: "Trenton",
    population: "9.3 million", timezone: "Eastern (ET)",
    majorCities: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison"],
    mapZoom: 8,
    overview: "New Jersey is the most densely populated state in the country and serves as a critical logistics gateway between New York City and Philadelphia, home to major pharmaceutical companies, financial services firms, and one of the world's busiest port complexes.",
    history: "New Jersey was assigned area code 201 in 1947, covering the entire state. New Jersey's extraordinary population density — the highest of any U.S. state — and its role as the suburban extension of New York City quickly created severe number demand. New Jersey has been split and overlaid more times than almost any comparably sized state. Northern New Jersey retained 201 but received the 551 overlay. Central New Jersey received 908 and later 848 (overlay of 732). Southern New Jersey, including the Atlantic City corridor, was assigned 609 (later overlaid with 856 for the Camden/Cherry Hill suburban Philadelphia region). New Jersey's pharmaceutical corridor along Routes 1 and 9 (home to Johnson & Johnson, Merck, Pfizer, Bristol-Myers Squibb) drives among the highest per-county business phone subscriptions in the nation.",
    businessContext: "New Jersey's pharmaceutical industry, Port Newark logistics complex, Jersey City financial services firms, and Atlantic City hospitality sector use specific area codes — 201 for the New York orbit, 856 for Philadelphia connections — to position within the competitive Northeast commercial corridor.",
  },
  "new mexico": {
    established: 1947, originalCode: "505", capital: "Santa Fe",
    population: "2.1 million", timezone: "Mountain (MT)",
    majorCities: ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell"],
    mapZoom: 7,
    overview: "New Mexico is anchored by Albuquerque's growing tech and film sector, the federal research and national lab economy at Los Alamos and Sandia, and Santa Fe's art market and government center.",
    history: "New Mexico entered the NANP in 1947 under area code 505, covering the entire state. The state operated under a single code for six decades, with its relatively modest population and sparse geography keeping subscriber demand within 505's capacity. However, Albuquerque's emergence as a tech hub (Intel has operated a major fabrication plant there since 1980) and the growth of Rio Rancho's suburban communities eventually required relief. The 575 area code was introduced in 2007 to serve southern and eastern New Mexico, including Las Cruces, Roswell, and Carlsbad Caverns country, while 505 was retained for Albuquerque, Santa Fe, and the Rio Grande corridor.",
    businessContext: "New Mexico businesses in federal research (Los Alamos National Laboratory, Sandia National Laboratories), film production (New Mexico's generous tax credits attract major Hollywood productions), and tourism use specific area codes to signal market positioning within the state's distinct economic zones.",
  },
  "new york": {
    established: 1947, originalCode: "212", capital: "Albany",
    population: "20.2 million", timezone: "Eastern (ET)",
    majorCities: ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse"],
    mapZoom: 7,
    overview: "New York State encompasses two radically different economic worlds: New York City, the world's financial capital, and Upstate New York, a region of manufacturing, agricultural, and mid-size university cities that operates on an entirely different economic scale.",
    history: "New York entered the NANP in 1947 with area code 212 for New York City and 518, 607, 716, and 914 for various Upstate regions. New York City alone has required unprecedented area code expansion: the original 212 was supplemented by 718 (outer boroughs, 1984), 917 (overlay, 1992), 646 (Manhattan overlay, 1999), 347 (outer boroughs overlay, 1999), 929 (outer boroughs overlay, 2011), and 332 (Manhattan additional overlay, 2017). Upstate codes have also multiplied: 585 was split from 716 for Rochester, 315 serves Syracuse and the North Country, 845 covers the Hudson Valley, and 607 handles the Southern Tier. Long Island's enormous suburban population required 516 and 631, plus subsequent overlays. New York's 212 area code remains one of the most prestigious in the world — in many industries, a 212 number is itself a form of status signaling.",
    businessContext: "In New York, the specific area code carries unusual weight: 212 signals Manhattan prestige and global financial credibility, 718 signals the outer boroughs and Brooklyn's creative economy, 516 signals Long Island's suburban professional community, and Upstate codes (585, 315, 518) signal regional business identity distinct from NYC's orbit.",
  },
  "north carolina": {
    established: 1947, originalCode: "704", capital: "Raleigh",
    population: "10.7 million", timezone: "Eastern (ET)",
    majorCities: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"],
    mapZoom: 7,
    overview: "North Carolina is one of the fastest-growing states in the Southeast, driven by Charlotte's financial sector — the second-largest banking center in the U.S. — and the Research Triangle's world-class technology and pharmaceutical cluster.",
    history: "North Carolina entered the NANP in 1947 with area code 704 covering most of the state. The western Piedmont and mountains were split off early with their own codes. The Research Triangle area (Raleigh, Durham, Chapel Hill) received 919. Winston-Salem and the Triad received 910 and later 336. Charlotte's explosive growth as America's banking capital — home to Bank of America and Wells Fargo's East Coast headquarters — required the 980 overlay alongside 704. The Triangle's tech and pharmaceutical boom required the 984 overlay for the Raleigh-Durham area. North Carolina's ongoing population boom, driven by migration from the Northeast and Midwest, has made it one of the most active markets for new area code allocations.",
    businessContext: "Charlotte's banking district (704/980), Research Triangle's life sciences and tech corridor (919/984), Triad's furniture and textiles legacy industries (336), and the Outer Banks tourism economy all use specific area codes to signal market position in a state whose diverse regions operate as distinct economic ecosystems.",
  },
  "north dakota": {
    established: 1947, originalCode: "701", capital: "Bismarck",
    population: "779,000", timezone: "Central (CT)",
    majorCities: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
    mapZoom: 7,
    overview: "North Dakota has maintained a single area code since 1947 and has experienced significant economic disruption and growth from the Bakken shale oil boom that transformed western North Dakota from the 2000s through the 2020s.",
    history: "North Dakota has operated under area code 701 since the NANP's launch in 1947 and has never needed to split or overlay its code. The state's population — approximately 779,000 — spread across a vast agricultural landscape has kept subscriber demand within manageable levels even as the Bakken oil boom brought tens of thousands of oil workers to previously tiny western North Dakota towns like Williston, Dickinson, and Minot. Fargo's growth as a mid-sized regional hub with a significant Microsoft software development center and health insurance operations has added urban subscriber density without pushing the 701 pool to capacity.",
    businessContext: "North Dakota businesses in oil field services, precision agriculture equipment (AGCO, CNH Industrial operations in the region), and Fargo's growing tech sector use 701 numbers to signal authentic Plains States roots in markets that value local presence and regional business relationships.",
  },
  ohio: {
    established: 1947, originalCode: "216", capital: "Columbus",
    population: "11.8 million", timezone: "Eastern (ET)",
    majorCities: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"],
    mapZoom: 7,
    overview: "Ohio is one of America's most economically diverse states, with five major metropolitan areas — Columbus, Cleveland, Cincinnati, Toledo, and Akron — each representing distinct industries and markets.",
    history: "Ohio entered the NANP in 1947 with area code 216 covering the entire state. Ohio's industrial density and multiple major metros drove aggressive splitting early. Cleveland retained 216 but was supplemented by the 440 overlay for the suburbs. Columbus received 614, with the 380 overlay added later. Cincinnati got 513, with 937 split off for Dayton. Toledo received 419, with the 567 overlay added as northwestern Ohio's subscriber base grew. Akron operates under 330, and the 234 overlay was added for northeastern Ohio. Ohio's role as a political bellwether state — routinely carrying both Republican and Democratic presidential candidates — gives its cities particular prominence in national media and political campaign advertising, driving additional commercial phone demand every two to four years.",
    businessContext: "Ohio's manufacturing companies (Cleveland's precision manufacturing), Columbus's insurance and financial services hub (Nationwide, Progressive), Cincinnati's consumer goods giants (Procter & Gamble, Kroger), and Akron's polymer and advanced materials industry all use specific Ohio area codes as geographic identifiers in their distinct B2B markets.",
  },
  oklahoma: {
    established: 1947, originalCode: "405", capital: "Oklahoma City",
    population: "4.0 million", timezone: "Central (CT)",
    majorCities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond"],
    mapZoom: 7,
    overview: "Oklahoma's economy is shaped by oil and gas production, aerospace and defense manufacturing, agriculture, and a growing technology sector centered on Oklahoma City's emergence as a mid-tier tech hub.",
    history: "Oklahoma entered the NANP in 1947 under area code 405. As Oklahoma City and Tulsa developed distinct economic identities, the state was split. Tulsa and northeastern Oklahoma received the 918 area code in 1985, recognizing Tulsa's role as an oil refining and aerospace center distinct from Oklahoma City's government and agriculture focus. Oklahoma City retained 405, which covers the central and western parts of the state. Oklahoma's oil economy has experienced repeated boom-bust cycles — each boom driving telecom demand spikes — while Tinker Air Force Base and aerospace companies like Boeing and Northrop Grumman have provided stable corporate subscriber bases independent of commodity cycles.",
    businessContext: "Oklahoma businesses in oil field services, aerospace maintenance and modification (Tulsa and Oklahoma City are major aircraft MRO centers), agriculture, and tribal gaming operations use local codes to signal regional presence in industries where personal relationships and local knowledge command premiums.",
  },
  oregon: {
    established: 1947, originalCode: "503", capital: "Salem",
    population: "4.3 million", timezone: "Pacific (PT)",
    majorCities: ["Portland", "Eugene", "Salem", "Gresham", "Hillsboro"],
    mapZoom: 7,
    overview: "Oregon is dominated by Portland's tech corridor — home to Nike, Adidas Americas, and Intel's largest fabrication campus outside of Ireland — and increasingly recognized as a second-tier tech hub drawing companies away from the Bay Area.",
    history: "Oregon launched under area code 503 in 1947, covering the entire state. Portland's growth and the emergence of the 'Silicon Forest' tech corridor along Highway 26 (anchored by Intel's Hillsboro campus) drove the need for relief. The 541 area code was introduced in 1995 to serve all of Oregon outside the Portland metropolitan area — a vast region including Eugene, Medford, Bend, and Astoria. Portland's continuing growth brought the 971 overlay in 2000. The 458 area code was added as a 541 overlay in 2010 for the southern and central Oregon regions. Oregon's lack of a sales tax has made it a retail and distribution hub for the Pacific Northwest, sustaining higher-than-average commercial subscriber demand.",
    businessContext: "Oregon's tech ecosystem (Intel, Nike, Adidas, Columbia Sportswear, Daimler Trucks North America all headquartered in or near Portland), craft beer and wine industry, timber and outdoor recreation economies use specific Portland (503/971) and rural Oregon (541/458) codes to signal precise market positioning.",
  },
  pennsylvania: {
    established: 1947, originalCode: "215", capital: "Harrisburg",
    population: "13.0 million", timezone: "Eastern (ET)",
    majorCities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"],
    mapZoom: 7,
    overview: "Pennsylvania spans two distinct worlds: Philadelphia's dense northeastern corridor with its pharmaceutical, financial, and education clusters, and Pittsburgh's resurgent tech and robotics economy in the west, connected by a largely rural and former-industrial center.",
    history: "Pennsylvania entered the NANP in 1947 under area code 215, covering the entire commonwealth. Pennsylvania's geographic and economic diversity — from Philadelphia's SEPTA-linked suburbs to Pittsburgh's steel-turned-tech economy to Allentown's manufacturing base to Erie's Lake Erie port — required extensive splitting. Philadelphia retained 215 but received the 267 overlay. The suburban counties of southeastern Pennsylvania received 610, later overlaid with 484. Central Pennsylvania including Harrisburg received 717, later overlaid with 223. The Lehigh Valley (Allentown-Bethlehem-Easton) received 610 and later 484. Pittsburgh retained 412 with the 878 overlay. Northeastern Pennsylvania including Scranton and Wilkes-Barre operates under 570, later overlaid with 272. Pennsylvania's combination of colonial history, pharmaceutical manufacturing (GlaxoSmithKline, AstraZeneca, and the Philadelphia biotech cluster), and Pittsburgh's robotics and autonomous vehicle research (Carnegie Mellon) drives diverse telecom demand.",
    businessContext: "Pennsylvania's pharmaceutical corridor (Philadelphia suburb Route 202), Pittsburgh's robotics and AI research cluster (CMU spinoffs), Allentown's advanced manufacturing, and Philadelphia's health system network (Penn Medicine, Jefferson, CHOP) all use specific PA area codes to signal which of the state's distinct economic regions they serve.",
  },
  "rhode island": {
    established: 1947, originalCode: "401", capital: "Providence",
    population: "1.1 million", timezone: "Eastern (ET)",
    majorCities: ["Providence", "Cranston", "Woonsocket", "Pawtucket", "East Providence"],
    mapZoom: 10,
    overview: "Rhode Island is the smallest state in the country and has maintained a single area code — 401 — since 1947, serving a dense economy of healthcare, defense, higher education, and maritime industries.",
    history: "Rhode Island has operated under area code 401 since the NANP's launch in 1947 and has never required a split or overlay. Despite being the smallest U.S. state by area, Rhode Island's population density is among the nation's highest, but the total subscriber count remains manageable within the 401 pool. Providence's revival as a mid-size city driven by Brown University and the Rhode Island School of Design, combined with the Navy's massive presence at Newport and the healthcare systems anchored by Lifespan and Care New England, provides stable telecom demand. Rhode Island's maritime heritage, jewelry manufacturing legacy (Providence was once the jewelry capital of the world), and emerging biotech sector keep 401 busy but not overwhelmed.",
    businessContext: "Rhode Island businesses in defense contracting (Naval Station Newport's submarine and surface warfare schools), healthcare systems, higher education (Brown, RISD, Providence College), and specialty manufacturing use 401 numbers to signal genuine Ocean State roots in tight-knit New England business networks.",
  },
  "south carolina": {
    established: 1947, originalCode: "803", capital: "Columbia",
    population: "5.3 million", timezone: "Eastern (ET)",
    majorCities: ["Columbia", "Charleston", "North Charleston", "Mount Pleasant", "Rock Hill"],
    mapZoom: 7,
    overview: "South Carolina has experienced dramatic economic transformation over the past three decades, shifting from textiles and tobacco to automotive manufacturing (BMW, Volvo, Mercedes-Benz Vans), aerospace (Boeing), and a booming Charleston port and tourism economy.",
    history: "South Carolina entered the NANP in 1947 under area code 803, covering the entire state. As South Carolina's coastal economy boomed around Charleston and Hilton Head, and as BMW's 1994 establishment of its only U.S. plant in Spartanburg began drawing suppliers and workers, the state's telecom needs diversified. The 864 area code was introduced for the Upstate region including Greenville, Spartanburg, and the BMW supplier corridor. The 843 area code was split off for the coastal region including Charleston and Myrtle Beach. Columbia and the Midlands retained 803. The 854 overlay was added for the coastal zone to accommodate continued tourism and port growth. South Carolina's growth in Boeing and Airbus supply chain operations has added significant industrial subscriber demand.",
    businessContext: "South Carolina's automotive and aerospace manufacturing corridor (BMW, Volvo, Mercedes-Benz Vans, and Boeing in Lowcountry), Charleston's port logistics, Myrtle Beach's hospitality industry, and Columbia's government and military (Fort Jackson) economy use local codes to target the state's three distinct economic regions.",
  },
  "south dakota": {
    established: 1947, originalCode: "605", capital: "Pierre",
    population: "910,000", timezone: "Central/Mountain (CT/MT)",
    majorCities: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"],
    mapZoom: 7,
    overview: "South Dakota has maintained a single area code since 1947 and is notable for its banking-friendly regulatory environment that has made it the headquarters of choice for major credit card operations.",
    history: "South Dakota has operated under area code 605 since the NANP's launch in 1947 and has never needed a split or overlay. Despite relatively modest population growth, South Dakota earned an outsized place in the U.S. financial system when a 1980 law abolished interest rate caps, prompting Citibank to relocate its credit card operations to Sioux Falls — eventually followed by Wells Fargo, First Premier Bank, and Capital One. This has made South Dakota a major hub for consumer credit operations, adding substantial corporate subscriber demand concentrated in Sioux Falls that has so far remained within the 605 pool's capacity. Rapid City serves as the gateway to Mount Rushmore and the Black Hills, driving significant tourism-related telecom activity.",
    businessContext: "South Dakota's banking and credit card operations (Citibank's credit card arm processes transactions under 605 numbers), Mount Rushmore and Black Hills tourism, Ellsworth Air Force Base, and agricultural commodities markets use 605 numbers in markets where a Sioux Falls financial address carries specific regulatory and legal advantages.",
  },
  tennessee: {
    established: 1947, originalCode: "615", capital: "Nashville",
    population: "7.1 million", timezone: "Central/Eastern (CT/ET)",
    majorCities: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"],
    mapZoom: 7,
    overview: "Tennessee has experienced explosive growth driven by Nashville's emergence as one of America's most dynamic cities, a major healthcare business hub (over 500 healthcare companies headquartered here), and music industry capital, plus the resurgent Memphis economy and the TVA industrial corridor.",
    history: "Tennessee entered the NANP in 1947 under area code 615, covering the entire state. Tennessee's four distinct economic cities — Nashville, Memphis, Knoxville, and Chattanooga — each developed their own economic identities that eventually justified separate codes. Memphis received 901, reflecting its role as FedEx's global hub and the Delta blues music industry center. Knoxville got 865 for the East Tennessee region (home to Oak Ridge National Laboratory and the University of Tennessee). Chattanooga received 423 along with the Tri-Cities region. Nashville retained 615 but received the 629 overlay as the city became one of America's fastest-growing metros, driven by corporate relocations (Oracle, Amazon), healthcare IT companies, and a booming tourism and entertainment economy.",
    businessContext: "Nashville's healthcare IT cluster (HCA Healthcare, Envision Healthcare, and hundreds of health services companies), Memphis's logistics corridor (FedEx, AutoZone, International Paper), Knoxville's government research (Oak Ridge), and Chattanooga's electric vehicle manufacturing (Volkswagen) all use specific Tennessee area codes as regional identity markers.",
  },
  texas: {
    established: 1947, originalCode: "214", capital: "Austin",
    population: "30.5 million", timezone: "Central (CT)",
    majorCities: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth"],
    mapZoom: 6,
    overview: "Texas is the second-most-populous state and one of the world's most economically significant jurisdictions, with major concentrations in energy (Houston), technology (Austin), finance and telecom (Dallas), and military (San Antonio).",
    history: "Texas launched with area code 214 in 1947, covering the entire state. Texas's explosive growth — second only to California in total subscribers — has required more area code additions than almost any other state. The original 214 has multiplied into 214, 469, and 972 for the Dallas-Fort Worth Metroplex. Houston spawned 713, 281, 832, and 346. San Antonio operates under 210, later receiving the 726 overlay. Austin — the fastest-growing large city in the U.S. — required 512 and then the 737 overlay as tech companies including Tesla, Oracle, and Apple relocated operations or expanded headquarters there. West Texas received 915 (El Paso) and 432 (Permian Basin). The Hill Country, Corpus Christi, and the Rio Grande Valley each have their own codes. Texas's continued population boom ensures ongoing area code expansion for decades to come.",
    businessContext: "Texas's specific area codes signal precise industry positioning: 713/832/346 signal Houston energy and port credibility, 214/469/972 signal Dallas financial and telecom corporate identity, 512/737 signal Austin tech startup credibility, and 210 signals San Antonio's military and bioscience community.",
  },
  utah: {
    established: 1947, originalCode: "801", capital: "Salt Lake City",
    population: "3.4 million", timezone: "Mountain (MT)",
    majorCities: ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem"],
    mapZoom: 7,
    overview: "Utah's 'Silicon Slopes' tech corridor — stretching from Salt Lake City through Provo and Orem along the Wasatch Front — has emerged as one of America's most dynamic tech ecosystems, with more software companies per capita than Silicon Valley.",
    history: "Utah entered the NANP in 1947 under area code 801, covering the entire state. Utah's tech sector, anchored by Brigham Young University's computer science programs and the Church of Jesus Christ of Latter-day Saints' global digital operations, began driving significant subscriber demand in the 1990s. The 435 area code was introduced in 1997 to serve rural Utah including the national parks corridor, St. George, and the Eastern Utah energy regions. The 801 area code retained the Wasatch Front urban core. As Silicon Slopes exploded — spawning publicly traded companies like Qualtrics, Domo, and dozens of unicorns — the 385 overlay was introduced in 2009 for the Salt Lake metropolitan area. Utah's tech sector has earned Silicon Slopes the reputation as America's most cost-effective alternative to Bay Area tech infrastructure.",
    businessContext: "Utah's tech companies, BYU's extensive alumni network in technology and finance, the LDS Church's global communications operations, and Park City's film festival and outdoor recreation economy all use 801 and 385 numbers to signal Wasatch Front credibility in industries where Salt Lake City has emerged as a legitimate tier-one tech hub.",
  },
  vermont: {
    established: 1947, originalCode: "802", capital: "Montpelier",
    population: "647,000", timezone: "Eastern (ET)",
    majorCities: ["Burlington", "South Burlington", "Rutland", "Barre", "Essex Junction"],
    mapZoom: 8,
    overview: "Vermont is the second-least-populous state and has maintained a single area code — 802 — since 1947, serving a distinctive economy of dairy farming, maple syrup production, craft brewing, skiing, and an unusually high concentration of socially conscious businesses.",
    history: "Vermont has operated under area code 802 since the NANP's launch in 1947 and has never needed to split or overlay its code. Vermont's small population — the second-smallest in the nation after Wyoming — and largely rural character have kept subscriber demand well within 802's capacity. Burlington's modest size as a university town (University of Vermont) and regional commercial center has added some urban telecom density without straining the pool. Vermont's 802 code has acquired a distinctive cultural identity associated with the state's progressive politics, farm-to-table economy, and brand of environmentally conscious business — exemplified by Ben & Jerry's founding in Burlington.",
    businessContext: "Vermont businesses in specialty food and beverage (craft beer, maple syrup, cheese), ski resort operations, farm-to-table hospitality, and Burlington's growing health technology sector use 802 numbers as markers of genuine Vermont provenance in markets where the 'Vermont brand' commands significant premium pricing.",
  },
  virginia: {
    established: 1947, originalCode: "703", capital: "Richmond",
    population: "8.7 million", timezone: "Eastern (ET)",
    majorCities: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Arlington"],
    mapZoom: 7,
    overview: "Virginia is home to the world's largest concentration of data centers (NoVA houses more data center capacity than anywhere else on earth), a massive federal government and defense contracting economy, and a growing Hampton Roads military-maritime complex.",
    history: "Virginia entered the NANP in 1947 under area code 703, covering the entire state. Northern Virginia's explosive growth as a Washington D.C. suburb and later as the global internet's physical backbone (Ashburn, Virginia hosts 70% of the world's internet traffic) drove the state's first splits. Richmond received 804, Hampton Roads received 757, and the Shenandoah Valley got 540. Northern Virginia retained 703 but received the 571 overlay as the NoVA data center corridor consumed enormous quantities of business phone numbers. Virginia's unique combination of Pentagon proximity (creating one of the world's densest defense contractor ecosystems) and internet infrastructure hosting (AWS, Microsoft Azure, and virtually every major CDN operates primary facilities in Virginia) makes it one of the nation's most telephonically active states relative to its population.",
    businessContext: "Northern Virginia's defense contracting ecosystem (Booz Allen Hamilton, SAIC, Leidos — all headquartered in or near the 703/571 area), data center operators, and federal agencies use specific Virginia area codes as credentials in a market where proximity to the Pentagon and federal agencies determines contract eligibility.",
  },
  washington: {
    established: 1947, originalCode: "206", capital: "Olympia",
    population: "7.8 million", timezone: "Pacific (PT)",
    majorCities: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"],
    mapZoom: 7,
    overview: "Washington State is defined by Seattle's extraordinary tech concentration — home to Amazon, Microsoft, Boeing, and a dense ecosystem of tech companies and startups — and an agricultural eastern half that produces a large share of America's apples, cherries, wheat, and wine.",
    history: "Washington entered the NANP in 1947 under area code 206, covering the entire state. Seattle's emergence as a global tech hub created intense subscriber demand that split the state into distinct zones. Eastern Washington received 509, reflecting Spokane's role as the Inland Northwest's commercial hub and the region's agricultural economy. The 253 area code was introduced for the Tacoma-Federal Way corridor, and 360 serves the remainder of western Washington outside Seattle (including Olympia, Bellingham, and the Olympic Peninsula). Seattle itself retained 206 but received the 564 overlay as Amazon, Microsoft's headquarters employees, and thousands of tech company offices consumed available numbers. The 425 area code covers the Eastside tech corridor (Bellevue, Redmond, Kirkland — where Microsoft's main campus is located) and has become closely associated with the tech industry globally.",
    businessContext: "Washington's specific area codes signal distinct identities: 206 represents Seattle proper and carries the weight of Amazon's and Boeing's headquarters, 425 signals the Eastside tech corridor where Microsoft and a dense cluster of AI and cloud companies operate, and 509 signals the entirely different agricultural and energy economy of eastern Washington.",
  },
  "west virginia": {
    established: 1947, originalCode: "304", capital: "Charleston",
    population: "1.8 million", timezone: "Eastern (ET)",
    majorCities: ["Charleston", "Huntington", "Parkersburg", "Morgantown", "Wheeling"],
    mapZoom: 7,
    overview: "West Virginia is undergoing significant economic transformation from its coal-mining heritage toward natural gas, chemical manufacturing, tourism (New River Gorge National Park), and technology-enabled remote work.",
    history: "West Virginia has operated under area code 304 since the NANP's launch in 1947. As the state's population declined through the coal industry's contraction and remained relatively small, the 304 number pool remained adequate for most of the state's history. However, Morgantown's growth as a university town (West Virginia University) and Huntington-Charleston's moderate industrial base eventually created the need for relief. The 681 overlay was introduced in 2013 to supplement 304 across the state. West Virginia's recent interest in becoming a destination for remote workers, combined with investment in broadband infrastructure in rural areas, has added new subscriber categories that weren't present in previous generations.",
    businessContext: "West Virginia businesses in natural gas extraction and pipeline operations, chemical manufacturing (the 'chemical valley' along the Kanawha River), WVU's research programs, and the emerging tourism economy at New River Gorge use 304 and 681 numbers to signal authentic Mountain State roots in industries where local relationships drive contracting decisions.",
  },
  wisconsin: {
    established: 1947, originalCode: "414", capital: "Madison",
    population: "5.9 million", timezone: "Central (CT)",
    majorCities: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
    mapZoom: 7,
    overview: "Wisconsin combines Milwaukee's manufacturing and financial heritage with Madison's world-class research university economy, the Fox Valley's paper and plastics industries, and Green Bay's agricultural and food processing dominance.",
    history: "Wisconsin launched under area code 414 in 1947, covering the entire state. As Wisconsin's major cities — Milwaukee, Madison, and Green Bay — developed distinct economic characters, the state was progressively split. Madison and south-central Wisconsin received 608, reflecting the state capital and University of Wisconsin's research economy. Green Bay and northeastern Wisconsin received 920, covering the Fox Valley's paper mill corridor and the Door County tourism region. Milwaukee retained 414 but received the 262 code for its suburban communities and 274 as an overlay. Wisconsin's manufacturing base — in sectors from precision tooling to dairy equipment to paper machinery — has sustained steady telecom demand that reflects the state's 'making things' economic identity.",
    businessContext: "Wisconsin businesses in dairy processing (America's Dairyland produces more cheese than any other state), brewing (Miller/Coors, hundreds of craft breweries), precision manufacturing (Briggs & Stratton, Harley-Davidson), and UW-Madison's biotech research use specific Wisconsin codes to signal which of the state's distinct industrial regions they represent.",
  },
  wyoming: {
    established: 1947, originalCode: "307", capital: "Cheyenne",
    population: "581,000", timezone: "Mountain (MT)",
    majorCities: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
    mapZoom: 7,
    overview: "Wyoming is the least-populous state in the country and has maintained a single area code — 307 — since 1947, serving an economy built on mineral extraction (coal, oil, natural gas, trona), ranching, and national park tourism.",
    history: "Wyoming has operated under area code 307 since the NANP's launch in 1947 and holds the distinction of being the least-populated state with the fewest active phone subscribers. Wyoming's economy of coal mining (the Powder River Basin in Campbell County produces 40% of all U.S. coal), oil and gas extraction, ranching, and Yellowstone and Grand Teton National Park tourism has never generated subscriber demand approaching 307's capacity. Despite the commodity booms in coal and natural gas that periodically transform small Wyoming towns like Gillette, Casper, and Rock Springs, the state's transient workforce typically uses mobile phones registered in their home states rather than acquiring Wyoming numbers. Wyoming's 307 code is one of the most exclusively recognized codes in the Mountain West.",
    businessContext: "Wyoming businesses in coal and mineral royalties, oil field services, cattle ranching, and national park tourism (Jackson Hole's luxury resort economy) use 307 numbers to signal genuine Wyoming presence in industries where land ownership, mineral rights, and outdoor recreation credentials require authentic local identity.",
  },
  "puerto rico": {
    established: 1995, originalCode: "787", capital: "San Juan",
    population: "3.2 million", timezone: "Atlantic (AT)",
    majorCities: ["San Juan", "Bayamón", "Carolina", "Ponce", "Guaynabo"],
    mapZoom: 9,
    overview: "Puerto Rico is a U.S. territory with its own distinct area codes — 787 and 939 — serving an economy anchored by pharmaceutical manufacturing, tourism, financial services, and a growing technology sector.",
    history: "Puerto Rico was originally served by area code 809, which covered all U.S. territories in the Caribbean including the U.S. Virgin Islands, the Dominican Republic, and others. In 1995, Puerto Rico received its own dedicated area code — 787 — as the NANP expanded to give individual territories distinct identities. Puerto Rico's pharmaceutical industry (the island produces a significant share of the world's pharmaceutical exports, including drugs manufactured for Johnson & Johnson, Bristol-Myers Squibb, and AbbVie) drove enough subscriber demand to require the 939 overlay in 2001. Act 20 and Act 22 tax incentive programs have attracted thousands of U.S. mainland businesses and entrepreneurs to establish Puerto Rico addresses, adding corporate subscriber demand.",
    businessContext: "Puerto Rico's pharmaceutical manufacturing sector, San Juan's financial services firms, and businesses leveraging Act 60 tax incentives use 787 and 939 numbers to signal genuine island presence to both U.S. mainland clients and Latin American markets that Puerto Rico uniquely bridges.",
  },
}

export function getStateInfo(stateSlug: string): StateInfo | null {
  return STATE_DATA[stateSlug.toLowerCase()] ?? null
}
